### ISSUE TITLE
Add a direct way to integrate Ask rest APIs with python web app

### ISSUE THREAD

**Issue by 0x0elliot** [Buscedv/Ask#85]
I believe this should be possible because Ask is written in flask. If we manage to pull this off, I would start using Ask in all of my web app projects.

**Comment by 0x0elliot** [comment]
for example, i have a project which looks like this:

/Project
- run.py
- __init__.py
- /static
- apis.ask

In apis.ask i have the API endpoints i want to use in my project. It would look something like this:

<code>
products = [
  {
    name: 'Product 1',
    price: 30.0,
    qty: 300
  },
  {
    name: 'Product 2',
    price: 15.5,
    qty: 20
  }
]

*import_for_flask('label')
@get('/api/v1/products'):
  respond({products: products})
</code>

and then I will import this to run.py as maybe a Blueprint? Or maybe something similar.

<code>
from flask import Flask
from flask_ask import integrate #made up library for better integration? 


def create_app():
    app = Flask(__name__)
    app.secret_key = secrets.token_hex(16)

    return app

app = create_app()

app.register_blueprint(integrate('apis.ask', "label"))

if __name__ == "__main__":
    app.run(debug=True,)

</code>

Then when the code is run, everything functions normally but you can also access /api/v1/products API endpoint that you wrote in ask through flask using the simple integration on the same server without needing to host the Ask server on some other port/server. I hope I got my point across.

**Comment by 0x0elliot** [comment]
Refer to <a href = "https://github.com/0x0elliot/ask_explaination/tree/main">this</a>

**Comment by Buscedv** [comment]
This is technically already possible, just not in the "blueprint" way you are suggesting. You can refer to this page in the documentation: https://docs.ask-lang.org/modules-and-libraries/importing-python-modules for more information.

Basically the way to do this now is to have a Ask script that imports python modules. These could be local .py files that are part of your project, or modules and libraries installed with ´pip´. The Ask app can then directly call functions in those files/modules. This means that you can have an Ask app with parts of it written in Python. I'm guessing what you are suggesting is a way to build a Python app with parts written in Ask? This shouldn't really be needed since Ask is a fully fledged programming language and most valid python code is also valid Ask code.
